((nil         . ((indent-tabs-mode             . nil)
                 (fill-column                  . 80)
                 (eval                         . (turn-on-fci-mode))))
 (erlang-mode . ((flycheck-erlang-include-path . ("../include"
                                                  "../../include"
                                                  "../deps"
                                                  "../../deps"
                                                  "../../"))
                 (flycheck-erlang-library-path . ("../ebin"
                                                  "../deps/accept/ebin"
                                                  "../deps/amqp_client/ebin"
                                                  "../deps/cowboy/ebin"
                                                  "../deps/cowlib/ebin"
                                                  "../deps/prometheus/ebin"
                                                  "../deps/prometheus_httpd/ebin"
                                                  "../deps/prometheus_process_collector/ebin"
                                                  "../deps/rabbit/ebin"
                                                  "../deps/rabbit_common/ebin"
                                                  "../deps/rabbitmq_management/ebin"
                                                  "../deps/rabbitmq_management_agent/ebin"
                                                  "../deps/rabbitmq_web_dispatch/ebin"
                                                  "../deps/ranch/ebin"
                                                  "../../ebin"
                                                  "../../deps/accept/ebin"
                                                  "../../deps/amqp_client/ebin"
                                                  "../../deps/cowboy/ebin"
                                                  "../../deps/cowlib/ebin"
                                                  "../../deps/prometheus/ebin"
                                                  "../../deps/prometheus_httpd/ebin"
                                                  "../../deps/prometheus_process_collector/ebin"
                                                  "../../deps/rabbit/ebin"
                                                  "../../deps/rabbit_common/ebin"
                                                  "../../deps/rabbitmq_management/ebin"
                                                  "../../deps/rabbitmq_management_agent/ebin"
                                                  "../../deps/rabbitmq_web_dispatch/ebin"
                                                  "../../deps/ranch/ebin"))
                 (erlang-indent-level          . 2))))
